### ISSUE TITLE
peer-to-peer code reviews

### ISSUE THREAD

**Issue by solorics** [haliljon/Portfolio-Project#11]
![image](https://user-images.githubusercontent.com/37203742/203721665-9f6f0ee2-685c-496a-9528-0ee0d9e23557.png)

### **Code Review** 💯 👍 

>. Good Job so far 👍 

>. Nice and neat codebase ✅ 

>. Good workFlow ✅ 

>. No Linters Errors ✅ 

>. Responsiveness on point ✅ 

>.You can Try and remove the duplicate close btn, and use the Figma image so when you click on the image it closes automatically. 😃

**Comment by haliljon** [comment]
Thank you 🙏
